# Numpy Learning


In [3]:
# import Numpy
import numpy as np

In [4]:
a=np.array([1,2,3] , dtype="int8")
b=np.array([[1,2,3,4] , [5,2,1,4] , [3,1,4,5]])
print(a , b)

[1 2 3] [[1 2 3 4]
 [5 2 1 4]
 [3 1 4 5]]


In [5]:
# shape Dimension
a.shape

(3,)

In [6]:
# type
b.dtype

dtype('int32')

In [7]:
# Dimension 
b.ndim

2

In [39]:
# Size
print(b.itemsize , "Item byte" , "\n","complete Byte")
print(  b.size * b.itemsize , "=", b.nbytes, "Combine byte" )

4 Item byte 
 complete Byte
48 = 48 Combine byte


In [8]:
# Get Specific Values
import numpy as np
a=np.array([1,2,3] , dtype="int8")
b=np.array([[1,2,3,4] , [5,2,1,4] , [3,1,4,5]])
c =np.array([[1,2,3,4,5] , [-1,-2,-3,-4,-5] , [-10,-20,-30,-40,-50]])

# specific_Value
specific_Value = c[2,1]

# specific_Row
specific_Row = c[0 ,4 :5 :6]

# specific_Row_with_start_value
specific_Row_with_start_value = c[1 ,1:-2 ]


# specific_Column
specific_col = c[: ,4 ]

# specific_Colum_with_start_value
specific_col_with_start_value = c[0:3: 2 ,1 ]




print("Array => \n" ,c , "\n specific_value  => " ,  specific_Value ,
'\n\n', "specific_R0w  => ", specific_Row , 
'\n\n',"specific_Row_with_start_value => " , specific_Row_with_start_value
     , '\n\n',"specific_Column  => ", specific_col, 
'\n\n',"specific_Column_with_start_value => " , specific_col_with_start_value )

Array => 
 [[  1   2   3   4   5]
 [ -1  -2  -3  -4  -5]
 [-10 -20 -30 -40 -50]] 
 specific_value  =>  -20 

 specific_R0w  =>  [5] 

 specific_Row_with_start_value =>  [-2 -3] 

 specific_Column  =>  [  5  -5 -50] 

 specific_Column_with_start_value =>  [  2 -20]


#### 

In [10]:
c[2,2]=5
print(c)

[[  1   2   3   4   5]
 [ -1  -2  -3  -4  -5]
 [-10 -20   5 -40 -50]]


In [23]:
# Multi Dimensional Array
da =np.array([[[1,2,3] , [4,5,6]] , [[7,8,9] , [10,11,12]]])
da.ndim
print(da)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [30]:
da[1: 1 :2] = [[6,3,4],[0,0,0]]
da

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 3, 4],
        [0, 0, 0]]])

In [28]:
type (2021)

int

In [44]:
tupple=(2021)

In [45]:
type(tupple)

int

In [40]:
np.zeros((2,3 ,3 ,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])