# Pandas Learning

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.3'

In [4]:
a=[1,2,3,4 ]
b=pd.Series(a , index = ["a","b","c" ,"d"] , dtype=object )
c=[1,2,3,4]
d=pd.Series(a , index = ["a","b","c" ,"d"] )
e = (b**2)*d
e

a     1
b     8
c    27
d    64
dtype: object

In [28]:
type (b)

pandas.core.series.Series

In [36]:
max(e)

64

In [37]:
min(e)

1

In [42]:
e[0:1]

a    1
dtype: object

In [14]:
b[ b <  3]

a    1
b    2
dtype: object

In [12]:
(b*d)[(b*d) > 12]

d    16
dtype: object

In [18]:
df = [['a','b' , 'c'],['d' ,'e','f']]
df1=pd.DataFrame(df )

In [56]:
df1

0  1  2
0  a  b  c
1  d  e  f

In [54]:
dics = {"label":[1,2,3 ] , "value":["45Rs" , "70RS" , "60RS"] , "index":[6,7,8,] ," name":["Affan","6","7"]  }
dics

{'label': [1, 2, 3],
 'value': ['45Rs', '70RS', '60RS'],
 'index': [6, 7, 8],
 ' name': ['Affan', '6', '7']}

In [58]:
dic1 = pd.DataFrame(dics , index=[1,2,3,])
dic1 

label value  index   name
1      1  45Rs      6  Affan
2      2  70RS      7      6
3      3  60RS      8      7

In [61]:
pd.read_csv('C:\\Users\\HP\\Desktop\\Book1.csv')

S.No    Name  Class  Age
0     1   Affan      6   12
1     2   faraz      5   32
2     3   usama      2   12
3     4  khalid      3   32

In [21]:
df =pd.read_csv('C:\\Users\\HP\\Desktop\\myfile.csv')

In [8]:
df.shape

(904, 42)

In [11]:
df.size

37968

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 904 entries, 0 to 903
Data columns (total 42 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Customer      904 non-null    object
 1   SC            904 non-null    int64 
 2   GW            904 non-null    int64 
 3   FW            904 non-null    int64 
 4   Design        904 non-null    object
 5   Color         904 non-null    object
 6   Version       904 non-null    object
 7   LD #          904 non-null    object
 8   Process       904 non-null    object
 9   Lot #         904 non-null    object
 10  Issue Date    904 non-null    object
 11  G Issue       904 non-null    object
 12  Pile          904 non-null    object
 13  Desize        904 non-null    object
 14  Bleach        904 non-null    object
 15  JT            904 non-null    object
 16  S 4 Mer       904 non-null    object
 17  Mer           904 non-null    object
 18  Eql           904 non-null    object
 19  Print   

In [20]:
pd.set_option('display.max_column' , 42)

In [22]:
schemaS =pd.read_csv('C:\\Users\\HP\\Desktop\\myfile.csv')

In [23]:
schemaS

Customer     SC  GW  FW       Design         Color  \
0    Alkaram Studio  51754  63  56       OP-046         Brown   
1    Alkaram Studio  51754  63  56       OP-046     Chocolate   
2    Alkaram Studio  51754  63  56       OP-046    Light Grey   
3    Alkaram Studio  51754  63  56       OP-046          Navy   
4    Alkaram Studio  51754  63  56       OP-046      Sky Blue   
..              ...    ...  ..  ..          ...           ...   
899  M/S Sale Dept.  57164  48  42   SS-20-FN-8       Mustard   
900  M/S Sale Dept.  57166  48  42  SS-20-FN-17         Green   
901  M/S Sale Dept.  57166  48  42  SS-20-FN-17        Purple   
902  M/S Sale Dept.  57168  47  42     FW-FN-37  Colorway #1    
903  M/S Sale Dept.  57168  47  42     FW-FN-37   Colorway #2   

                                             Version           LD #  \
0                                03-0016/ BROWN /         03-0016/    
1                          04-0538/01 CHOCOLATE /       04-0538/01    
2                         03-0687/01 LIGHT GREY /       03-0687/01    
3                                  SBD-1513  / Navy       SBD-1513    
4                           05-0614/02 SKY BLUE /       05-0614/02    
..                                               ...            ...   
899  FP-192626/2 SS20 FN 08 SHIRT BUSSER/2-MUSTARD    FP-192626/2     
900      FP-192622/1 SS20 FN 17 SHIRT FLAT/1-GREEN    FP-192622/1     
901     FP-192622/2 SS20 FN 17 SHIRT FLAT/2-PURPLE    FP-192622/2     
902                            06-0061/01 BLACK /       06-0061/01    
903                            06-0061/01 BLACK /       06-0061/01    

              Process       Lot # Issue Date G Issue    Pile  Desize  Bleach  \
0              Dyeing  AKOS-2630D  12-Sep-19   2,023       0       0       0   
1              Dyeing  AKOS-2630C  12-Sep-19   2,400       0       0       0   
2              Dyeing  AKOS-2630B  12-Sep-19   2,400       0       0       0   
3              Dyeing  AKOS-2630A  12-Sep-19   2,400       0       0       0   
4              Dyeing   AKOS-2630  12-Sep-19   2,400       0       0       0   
..                ...         ...        ...     ...     ...     ...     ...   
899   BUSSER PRINTING   AKOS-4037  17-Oct-19  14,047  14,047  14,047  14,047   
900  FLATBED PRINTING   AKOS-3934  15-Oct-19  14,039  14,039  14,039  14,039   
901  FLATBED PRINTING   AKOS-3916  14-Oct-19  14,037  14,037  14,000  14,000   
902            Dyeing     AK-4015  17-Oct-19   4,271   4,271   4,271   4,271   
903            Dyeing    AK-4015A  17-Oct-19   4,271   4,271   4,271   4,271   

    JT S 4 Mer     Mer     Eql Print Bal Print Dyeing Bal Dye Wash Cure Steam  \
0    0       0       0       0     0     2,023      0   2,023    0    0     0   
1    0       0       0       0     0     2,400      0   2,400    0    0     0   
2    0       0       0       0     0     2,400      0   2,400    0    0     0   
3    0       0       0       0     0     2,400      0   2,400    0    0     0   
4    0       0       0       0     0     2,400      0   2,400    0    0     0   
..  ..     ...     ...     ...   ...       ...    ...     ...  ...  ...   ...   
899  0       0       0       0     0    14,047      0  14,047    0    0     0   
900  0  14,039       0       0     0    14,039      0  14,039    0    0     0   
901  0  14,000  14,000  14,000     0    14,037      0  14,037    0    0     0   
902  0   4,271       0       0     0     4,271      0   4,271    0    0     0   
903  0   4,271       0       0     0     4,271      0   4,271    0    0     0   

    Finish Bal Finish Calen Sanfo FFD  FFD Date Bal FFD FFD%  Hold Roll  \
0        0      2,023     0     0   0  0-Jan-00   2,023   0%     0    0   
1        0      2,400     0     0   0  0-Jan-00   2,400   0%     0    0   
2        0      2,400     0     0   0  0-Jan-00   2,400   0%     0    0   
3        0      2,400     0     0   0  0-Jan-00   2,400   0%     0    0   
4        0      2,400     0     0   0  0-Jan-00   2,400   0%     0  

In [12]:
pan_dic = {
    "first" :pd.Series([100,101,102,103] , index=["chair" , "books" , "Notes","register"]),
    "second" : pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
     "3" :pd.Series([100,101,102,103] , index=["chair" , "books" , "Notes","register"]),
    "4" : pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
     "5" :pd.Series([100,101,102,103] , index=["chair" , "books" , "Notes","register"]),
    "6" : pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
     "7" :pd.Series([100,101,102,103] , index=["chair" , "books" , "Notes","register"]),
    "8" : pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
     "9" :pd.Series([100,101,102,103] , index=["chair" , "books" , "Notes","register"]),
    "10": pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
     "11":pd.Series([100,101,102,103] , index=["chair" , "books" , "Notes","register"]),
    "12": pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
     "13":pd.Series([100,101,102,103,104],index=["chair" , "books" , "Notes","register" , "pen"]),
    "14": pd.Series([200,201,202,203] , index=["chair" , "books" , "Notes","register"]),
}

In [13]:
df = pd.DataFrame(pan_dic)
df

first  second      3      4      5      6      7      8      9  \
Notes     102.0   202.0  102.0  202.0  102.0  202.0  102.0  202.0  102.0   
books     101.0   201.0  101.0  201.0  101.0  201.0  101.0  201.0  101.0   
chair     100.0   200.0  100.0  200.0  100.0  200.0  100.0  200.0  100.0   
pen         NaN     NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
register  103.0   203.0  103.0  203.0  103.0  203.0  103.0  203.0  103.0   

             10     11     12   13     14  
Notes     202.0  102.0  202.0  102  202.0  
books     201.0  101.0  201.0  101  201.0  
chair     200.0  100.0  200.0  100  200.0  
pen         NaN    NaN    NaN  104    NaN  
register  203.0  103.0  203.0  103  203.0

In [14]:
df.index

Index(['Notes', 'books', 'chair', 'pen', 'register'], dtype='object')

In [18]:
df.ndim

2

In [23]:
df.columns

Index(['first', 'second', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14'],
      dtype='object')

In [31]:

pd.DataFrame(df ,  index=["Notes" , "chair"] , columns =['first' , '5'])

first      5
Notes  102.0  102.0
chair  100.0  100.0

# we can learn Data fram with Airthmtic logic


In [2]:
 arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [3]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [4]:
 arr.astype(np.float)

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [5]:
int_array = np.arange(10)

In [6]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a =np.array([2,3,4])

In [8]:
a

array([2, 3, 4])

In [16]:
empty_uint32 = np.empty(8, dtype='u4')

In [17]:
empty_uint32

array([2037674093, 1935764768,  543450475, 1634890337, 1769414777,
       1629513844, 1696623724, 1701668204], dtype=uint32)